fix bug when domain id is set
with export ROS_DOMAIN_ID=8

I get following error
Traceback (most recent call last):
  File "/app/formant_ros2_adapter/scripts/main.py", line 18, in <module>
    rclpy.init(domain_id=ROS2_DOMAIN_ID)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 89, in init
    return context.init(args, domain_id=domain_id)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/context.py", line 64, in init
    if domain_id is not None and domain_id < 0:
TypeError: '<' not supported between instances of 'str' and 'int'

wrapping the env variable retrieval in int allows this to work